#!/bin/sh

instances="mpz_class mpq_class int8_t int16_t int32_t int64_t float32_t float64_t float96_t float128_t"

mpz_class_XFAIL_TESTS=
mpq_class_XFAIL_TESTS=
int8_t_XFAIL_TESTS=
int16_t_XFAIL_TESTS=
int32_t_XFAIL_TESTS=
int64_t_XFAIL_TESTS=
float32_t_XFAIL_TESTS=
float64_t_XFAIL_TESTS=
float96_t_XFAIL_TESTS=
float128_t_XFAIL_TESTS=

check_PROGRAMS=$(MAKEFLAGS='' make -s print_check_PROGRAMS)

# NOTE: mpz_class must be the first in the list.  See Makefile.am.
for k in $instances 
do
	echo "**************************** " $k " ****************************"
	make check TESTS="$check_PROGRAMS" TEST_CPPFLAGS="\"-DTBD_Shape=BD_Shape<$k>\""
	make clean
done
