#!/bin/sh

# NOTE: mpz_class must be the first in the list.  See Makefile.am.
instances="mpz_class float double mpq_class int8_t int16_t int32_t int64_t"

mpz_class_XFAIL_TESTS=
mpq_class_XFAIL_TESTS=
int8_t_XFAIL_TESTS=
int16_t_XFAIL_TESTS=
int32_t_XFAIL_TESTS=
int64_t_XFAIL_TESTS=
float_XFAIL_TESTS=
double_XFAIL_TESTS=
long_double_XFAIL_TESTS=

check_PROGRAMS=$(MAKEFLAGS='' make -s print_check_PROGRAMS)

for k in $instances 
do
	echo "**************************** " $k " ****************************"
	eval xfail_tests='"$'$k'_XFAIL_TESTS"'
	make check TESTS="$check_PROGRAMS" TEST_CPPFLAGS="\"-DTBD_Shape=BD_Shape<$k>\"" XFAIL_TESTS=$xfail_tests || exit 1
	make clean
done
