#!/bin/sh
temp_file=`mktemp /tmp/bump_copyright_years.XXXXXXXXXX` || exit 1
for k in `find . -type f`
do
  sed -e "s/Copyright (C) 2010-2011 BUGSENG srl/Copyright (C) 2010-2012 BUGSENG srl/g" <$k >$temp_file
  chmod --reference=$k $temp_file
  mv -f $temp_file $k
done
