#!/bin/sh
# Copyright (C) 2001-2010 Roberto Bagnara <bagnara@cs.unipr.it>
# Copyright (C) 2010-2011 BUGSENG srl (http://bugseng.com)
#
# This file is part of the Parma Polyhedra Library (PPL).
#
# The PPL is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# The PPL is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02111-1307, USA.
#
# For the most up-to-date information see the Parma Polyhedra Library
# site: http://www.cs.unipr.it/ppl/ .

if [ $# -ne 1  ]; then
        echo "Usage: `basename $0` file.bib" 1>&2
        exit 1
fi
# Note: this has been tested with bibtex2html version 1.92.
bibtex2html -no-header -quiet -sort-as-bibtex -nodoc -noabstract \
            -nobibsource -style alpha --output - \
            -named-field SOURCE "Source code" $1 \
    | sed -f generate_dox_biblio.sed >`basename $1 .bib`.dox
