#!/bin/sh
# Copyright (C) 2001-2010 Roberto Bagnara <bagnara@cs.unipr.it>
# Copyright (C) 2010-2011 BUGSENG srl (http://bugseng.com)
#
# This file is part of the Parma Polyhedra Library (PPL).
#
# The PPL is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at your
# option) any later version.
#
# The PPL is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02111-1307, USA.
#
# For the most up-to-date information see the Parma Polyhedra Library
# site: http://www.cs.unipr.it/ppl/ .

# See http://www.gnu.org/software/help2man/ for the help2man utility.
help2man --name="obtain information about an installation of the Parma Polyhedra Library" -N --include=../doc/ppl-config_extra_man_text ppl-config >../doc/ppl-config.1
help2man --name="a PPL-based mixed integer programming problem solver" -N --include=../demos/ppl_lpsol/ppl_lpsol_extra_man_text ppl_lpsol >../demos/ppl_lpsol/ppl_lpsol.1
help2man --name="a PPL-based parametric integer programming problem solver" -N --include=../demos/ppl_pips/ppl_pips_extra_man_text ppl_pips >../demos/ppl_pips/ppl_pips.1
help2man --name="a PPL-based program for vertex/facet enumeration of convex polyhedra" -N --include=../demos/ppl_lcdd/ppl_lcdd_extra_man_text ppl_lcdd >../demos/ppl_lcdd/ppl_lcdd.1
