#!/bin/sh
if [ $# -ne 1  ]; then
        echo "Usage: `basename $0` file.bib" 1>&2
        exit 1
fi
bibtex2html -no-header -quiet -sort-as-bibtex -nodoc -noabstract -nobibsource -style alpha -named-field SOURCE "Source code" $1
name=`basename $1 .bib`
sed -f bib2html1.sed <$name.html | sed -f bib2html2.sed >$name.dox
