s/<hr><em>This file has been generated by//g
/>bibtex2html</d
s/[ab]2002/2002/g
s/table>/DL>/g
/<tr valign="top">/d
/<td align="right">/d
s/^\(\[[^ ][A-Za-z0-9 ]*\]\)$/<DT> \1 <\/DT>/g
/^\[ /d
/<\/td>/d
s/<td>/<DD>/g
s/<\/tr>/<\/DD>/g
s/<br \/>//g
