#!/bin/sh
help2man --name="obtain information about an installation of the Parma Polyhedra Library" -N --include=ppl-config_extra_man_text ppl-config >ppl-config.1
help2man --name="a PPL-based linear programming problem solver" -N --include=ppl_lpsol_extra_man_text ppl_lpsol >ppl_lpsol.1
help2man --name="a PPL-based program for vertex/facet enumeration of convex polyhedra" -N --include=ppl_lcdd_extra_man_text ppl_lcdd >ppl_lcdd.1
